require_relative '../lib/twocheckout_client'
require 'test/unit'

TEST_ORDER_PAYLOAD = {
  :Items   => [
    {
      :Name => 'test',
      :Description => 'test',
      :IsDynamic => true,
      :Tangible => false,
      :PurchaseType => 'PRODUCT',
      :Quantity => 1,
      :Price => {
        :Amount => 1,
        :Type => 'CUSTOM'
      }
    }
  ],
  :BillingDetails => {
    :FirstName => 'John',
    :LastName => 'Doe',
    :Email => 'john.doe@test.com',
    :CountryCode => 'US',
    :Address1 => '123 Test St',
    :City => 'Columbus',
    :State => 'OH',
    :Zip => '43123'
  },
  :PaymentDetails => {
    :Type => 'TEST',
    :Currency => 'USD',
    :PaymentMethod => {
      :CardType => 'mastercard',
      :CardNumber => '5555555555554444',
      :CCID => '123',
      :ExpirationMonth => '10',
      :ExpirationYear => '2026',
      :HolderName => 'John Doe',
      :Vendor3DSReturnURL => 'www.success.com',
      :Vendor3DSCancelURL => 'www.success.com'
    }
  }
}

TEST_IPN = {
  GIFT_ORDER: "0",
  SALEDATE: "2021-09-27 13:04:29",
  PAYMENTDATE: "2021-09-27 13:04:34",
  REFNO: "99999999",
  REFNOEXT: "9845321b-f2b4-4647-a81e-1eeebfd4c226",
  SHOPPER_REFERENCE_NUMBER: "",
  ORDERNO: "13188",
  ORDERSTATUS: "COMPLETE",
  PAYMETHOD: "Visa/MasterCard",
  PAYMETHOD_CODE: "CCVISAMC",
  FIRSTNAME: "John",
  LASTNAME: "Doe",
  COMPANY: "",
  REGISTRATIONNUMBER: "",
  FISCALCODE: "",
  TAX_OFFICE: "",
  CBANKNAME: "",
  CBANKACCOUNT: "",
  ADDRESS1: "55 White Cowley Court",
  ADDRESS2: "tewtr 2",
  CITY: "Brasov",
  STATE: "-",
  ZIPCODE: "29636",
  COUNTRY: "Romania",
  COUNTRY_CODE: "ro",
  PHONE: "",
  FAX: "",
  CUSTOMEREMAIL: "john.doe@test.com",
  FIRSTNAME_D: "John",
  LASTNAME_D: "Doe",
  COMPANY_D: "",
  ADDRESS1_D: "123 test st",
  ADDRESS2_D: "tewtr 2",
  CITY_D: "test",
  STATE_D: "-",
  ZIPCODE_D: "29636",
  COUNTRY_D: "Romania",
  COUNTRY_D_CODE: "ro",
  PHONE_D: "",
  EMAIL_D: "john.doe@test.com",
  IPADDRESS: "192.168.1.1",
  IPCOUNTRY: "Romania",
  COMPLETE_DATE: "2021-09-27 13:04:36",
  TIMEZONE_OFFSET: "GMT+03:00",
  CURRENCY: "USD",
  LANGUAGE: "en",
  ORDERFLOW: "REGULAR",
  IPN_PID: ["37179430"],
  IPN_PNAME: ["Cart_781cc275-243c-405b-b5f7-b35986fd9233"],
  IPN_PCODE: [""],
  IPN_EXTERNAL_REFERENCE: ["20210927100413"],
  IPN_INFO: [""],
  IPN_QTY: ["1"],
  IPN_PRICE: ["95.00"],
  IPN_VAT: ["0.00"],
  IPN_VAT_RATE: ["0.0000"],
  IPN_VER: ["1"],
  IPN_DISCOUNT: ["0.00"],
  IPN_PROMOTION_CATEGORY: [""],
  IPN_PROMONAME: [""],
  IPN_PROMOCODE: [""],
  IPN_ORDER_COSTS: ["0"],
  IPN_SKU: [""],
  IPN_PARTNER_CODE: "",
  IPN_PGROUP: ["0"],
  IPN_PGROUP_NAME: [""],
  MESSAGE_ID: "251610655414",
  MESSAGE_TYPE: "COMPLETE",
  IPN_LICENSE_PROD: ["37179430"],
  IPN_LICENSE_TYPE: ["REGULAR"],
  IPN_LICENSE_REF: ["JOCX9W18NM"],
  IPN_LICENSE_EXP: ["9999-12-31 23:59:59"],
  IPN_LICENSE_START: ["2021-09-27 13:04:34"],
  IPN_LICENSE_LIFETIME: ["YES"],
  IPN_LICENSE_ADDITIONAL_INFO: [""],
  IPN_DELIVEREDCODES: [""],
  IPN_DOWNLOAD_LINK: "",
  IPN_TOTAL: ["95.00"],
  IPN_TOTALGENERAL: "95.00",
  IPN_SHIPPING: "0.00",
  IPN_SHIPPING_TAX: "0.00",
  AVANGATE_CUSTOMER_REFERENCE: "938845083",
  EXTERNAL_CUSTOMER_REFERENCE: "9ddc7cb4-1d1e-4044-8698-81d0181f624c",
  IPN_PARTNER_MARGIN_PERCENT: "0.00",
  IPN_PARTNER_MARGIN: "0.00",
  IPN_EXTRA_MARGIN: "0.00",
  IPN_EXTRA_DISCOUNT: "0.00",
  IPN_COUPON_DISCOUNT: "0.00",
  IPN_LINK_SOURCE: "TEST",
  IPN_COMMISSION: "3.6766",
  REFUND_TYPE: "",
  CHARGEBACK_RESOLUTION: "NONE",
  CHARGEBACK_REASON_CODE: "",
  TEST_ORDER: "1",
  IPN_ORDER_ORIGIN: "Web",
  FRAUD_STATUS: "APPROVED",
  CARD_TYPE: "visa",
  CARD_LAST_DIGITS: "1111",
  CARD_EXPIRATION_DATE: "11/22",
  GATEWAY_RESPONSE: "Approved",
  IPN_DATE: "20210927141645",
  FX_RATE: "1",
  FX_MARKUP: "0",
  PAYABLE_AMOUNT: "91.32",
  PAYOUT_CURRENCY: "USD",
  VENDOR_CODE: "123456789012",
  PROPOSAL_ID: "",
  HASH: "78f30479cef349691d4eaeecf16f1c52",
  'bad_key' => 'this should be skipped'
}

TEST_CONVERT_PLUS_PARAMS = {
  "address" => "Test Address",
  "city" => "Columbus",
  "country" => "US",
  "name" => "Customer 2Checkout",
  "phone" => "0770678987",
  "zip" => "12345",
  "email" => "testcustomer@2Checkout.com",
  "company-name" => "Verifone",
  "state" => "California",
  "ship-name" => "Customer 2Checkout",
  "ship-address" => "Test Address",
  "ship-city" => "Columbus",
  "ship-country" => "US",
  "ship-state" => "California",
  "ship-email" => "testcustomer@2Checkout.com",
  "prod" => "Buy link Dynamic product test product from API",
  "price" => "1",
  "qty" => "1",
  "type" => "PRODUCT",
  "tangible" => "0",
  "return-url" => "http://tcoLib.example/paymentCallback.php",
  "return-type" => "redirect",
  "order-ext-ref" => "CustOrd100",
  "item-ext-ref" => "20210423094943",
  "customer-ext-ref" => "testcustomer@2Checkout.com",
  "currency" => "usd",
  "language" => "en",
  "test" => "1",
  "merchant" => "250111206876",
  "dynamic" => "1"
}



module TwocheckoutClient
  Test::Unit.at_start do
      TCO_TEST_CLIENT = TwocheckoutClient::Client.new(
      merchant_code: '123456789012',
      secret_word: 'foo',
      secret_key: 'bar'
      )
  end
end