require_relative '../lib/twocheckout_client'
require 'test/unit'

TEST_ORDER_PAYLOAD = {
  :Items   => [
    {
      :Name => 'test',
      :Description => 'test',
      :IsDynamic => true,
      :Tangible => false,
      :PurchaseType => 'PRODUCT',
      :Quantity => 1,
      :Price => {
        :Amount => 1,
        :Type => 'CUSTOM'
      }
    }
  ],
  :BillingDetails => {
    :FirstName => 'John',
    :LastName => 'Doe',
    :Email => 'john.doe@test.com',
    :CountryCode => 'US',
    :Address1 => '123 Test St',
    :City => 'Columbus',
    :State => 'OH',
    :Zip => '43123'
  },
  :PaymentDetails => {
    :Type => 'TEST',
    :Currency => 'USD',
    :PaymentMethod => {
      :CardType => 'mastercard',
      :CardNumber => '5555555555554444',
      :CCID => '123',
      :ExpirationMonth => '10',
      :ExpirationYear => '2026',
      :HolderName => 'John Doe',
      :Vendor3DSReturnURL => 'www.success.com',
      :Vendor3DSCancelURL => 'www.success.com'
    }
  }
}

TEST_IPN = {
  GIFT_ORDER: "0",
  SALEDATE: "2023-06-09 15:26:18",
  PAYMENTDATE: "2023-06-09 15:31:18",
  REFNO: "211153389",
  REFNOEXT: "REST_API_AVANGTE",
  SHOPPER_REFERENCE_NUMBER: "",
  ORDERNO: "25430",
  ORDERSTATUS: "COMPLETE",
  PAYMETHOD: "Visa/MasterCard",
  PAYMETHOD_CODE: "CCVISAMC",
  FIRSTNAME: "Customer",
  LASTNAME: "2Checkout",
  COMPANY: "",
  REGISTRATIONNUMBER: "",
  FISCALCODE: "",
  TAX_OFFICE: "",
  CBANKNAME: "",
  CBANKACCOUNT: "",
  ADDRESS1: "Test Address",
  ADDRESS2: "",
  CITY: "LA",
  STATE: "DF",
  ZIPCODE: "70403-900",
  COUNTRY: "United States of America",
  COUNTRY_CODE: "us",
  PHONE: "556133127400",
  FAX: "",
  CUSTOMEREMAIL: "customer@2Checkout.com",
  FIRSTNAME_D: "Customer",
  LASTNAME_D: "2Checkout",
  COMPANY_D: "",
  ADDRESS1_D: "Test Address",
  ADDRESS2_D: "",
  CITY_D: "LA",
  STATE_D: "DF",
  ZIPCODE_D: "70403-900",
  COUNTRY_D: "United States of America",
  COUNTRY_D_CODE: "us",
  PHONE_D: "556133127400",
  EMAIL_D: "customer@2Checkout.com",
  IPADDRESS: "91.220.121.21",
  IPCOUNTRY: "Romania",
  COMPLETE_DATE: "2023-06-09 15:31:23",
  TIMEZONE_OFFSET: "GMT+03:00",
  CURRENCY: "RON",
  LANGUAGE: "en",
  ORDERFLOW: "REGULAR",
  IPN_PID: ["40898000"],
  IPN_PNAME: ["Dynamic product"],
  IPN_PCODE: [""],
  IPN_EXTERNAL_REFERENCE: [""],
  IPN_INFO: [""],
  IPN_QTY: ["1"],
  IPN_PRICE: ["0.01"],
  IPN_VAT: ["0.00"],
  IPN_VAT_RATE: ["0.0000"],
  IPN_VER: ["1"],
  IPN_DISCOUNT: ["0.00"],
  IPN_PROMOTION_CATEGORY: [""],
  IPN_PROMONAME: [""],
  IPN_PROMOCODE: [""],
  IPN_ORDER_COSTS: ["0"],
  IPN_SKU: [""],
  IPN_PARTNER_CODE: "",
  IPN_PGROUP: ["0"],
  IPN_PGROUP_NAME: [""],
  MESSAGE_ID: "254498854202",
  MESSAGE_TYPE: "COMPLETE",
  IPN_LICENSE_PROD: ["40898000"],
  IPN_LICENSE_TYPE: ["REGULAR"],
  IPN_LICENSE_REF: ["XRILXB9ZI3"],
  IPN_LICENSE_EXP: ["9999-12-31 23:59:59"],
  IPN_LICENSE_START: ["2023-06-09 15:31:18"],
  IPN_LICENSE_LIFETIME: ["YES"],
  IPN_LICENSE_ADDITIONAL_INFO: [""],
  IPN_DELIVEREDCODES: [""],
  IPN_DOWNLOAD_LINK: "",
  IPN_TOTAL: ["0.01"],
  IPN_TOTALGENERAL: "0.01",
  IPN_SHIPPING: "0.00",
  IPN_SHIPPING_TAX: "0.00",
  AVANGATE_CUSTOMER_REFERENCE: "756227060",
  EXTERNAL_CUSTOMER_REFERENCE: "IOUER",
  IPN_PARTNER_MARGIN_PERCENT: "0.00",
  IPN_PARTNER_MARGIN: "0.00",
  IPN_EXTRA_MARGIN: "0.00",
  IPN_EXTRA_DISCOUNT: "0.00",
  IPN_COUPON_DISCOUNT: "0.00",
  IPN_LINK_SOURCE: "testAPI.com",
  IPN_COMMISSION: "2.7678",
  REFUND_TYPE: "",
  CHARGEBACK_RESOLUTION: "NONE",
  CHARGEBACK_REASON_CODE: "",
  TEST_ORDER: "0",
  IPN_ORDER_ORIGIN: "API",
  FRAUD_STATUS: "APPROVED",
  CARD_TYPE: "mastercard",
  CARD_LAST_DIGITS: "5547",
  CARD_EXPIRATION_DATE: "05/27",
  GATEWAY_RESPONSE: "Approved",
  IPN_DATE: "20230612194811",
  FX_RATE: "0.20810660205937",
  FX_MARKUP: "4",
  PAYABLE_AMOUNT: "-0.57",
  PAYOUT_CURRENCY: "USD",
  VENDOR_CODE: "250111206876",
  PROPOSAL_ID: "",
  HASH: "68ca6b208fd204e07b651dacd8a55340",
  SIGNATURE_SHA2_256: "492e89fb51bd6b4948f9904d2eb041399494afca17dd5c88e982015e7429295c",
  SIGNATURE_SHA3_256: "605f2195d0d6c918f50909acd68a0c770320fc6f20a60e6ef396c41450882222",
  'bad_key' => 'this should be skipped'
}

TEST_CONVERT_PLUS_PARAMS = {
  "address" => "Test Address",
  "city" => "Columbus",
  "country" => "US",
  "name" => "Customer 2Checkout",
  "phone" => "0770678987",
  "zip" => "12345",
  "email" => "testcustomer@2Checkout.com",
  "company-name" => "Verifone",
  "state" => "California",
  "ship-name" => "Customer 2Checkout",
  "ship-address" => "Test Address",
  "ship-city" => "Columbus",
  "ship-country" => "US",
  "ship-state" => "California",
  "ship-email" => "testcustomer@2Checkout.com",
  "prod" => "Buy link Dynamic product test product from API",
  "price" => "1",
  "qty" => "1",
  "type" => "PRODUCT",
  "tangible" => "0",
  "return-url" => "http://tcoLib.example/paymentCallback.php",
  "return-type" => "redirect",
  "order-ext-ref" => "CustOrd100",
  "item-ext-ref" => "20210423094943",
  "customer-ext-ref" => "testcustomer@2Checkout.com",
  "currency" => "usd",
  "language" => "en",
  "test" => "1",
  "merchant" => "250111206876",
  "dynamic" => "1"
}



module TwocheckoutClient
  Test::Unit.at_start do
      TCO_TEST_CLIENT = TwocheckoutClient::Client.new(
      merchant_code: '123456789012',
      secret_word: 'foo',
      secret_key: 'bar'
      )
  end
end